/**
 * 🤖 Butler Generated Scripts Service
 * Saves and loads Python scripts generated by Butler AI.
 * Scripts are persisted in AsyncStorage and shown in the Scripts tab.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

const BUTLER_SCRIPTS_KEY = '@butler_generated_scripts_v1';

export interface ButlerScript {
  id: string;
  title: string;
  script: string;
  category: string;
  description: string;
  tags: string[];
  requirements: string[];
  createdAt: string;
  source: 'butler_ai';
  notes?: string;  // User annotations / personal notes
}

/**
 * Extract the first ```python ... ``` code block from a message string.
 * Returns the code string or null if no block found.
 */
export function extractPythonCode(content: string): string | null {
  // Match ```python ... ``` or ``` ... ``` blocks
  const match = content.match(/```(?:python)?\s*\n([\s\S]*?)```/);
  if (match && match[1]) {
    const code = match[1].trim();
    // Must look like Python (has imports or print or def or class)
    if (code.length > 20 && /import |def |class |print\(|#/.test(code)) {
      return code;
    }
  }
  return null;
}

/**
 * Extract ALL Python code blocks from a message.
 */
export function extractAllPythonBlocks(content: string): string[] {
  const blocks: string[] = [];
  const regex = /```(?:python)?\s*\n([\s\S]*?)```/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(content)) !== null) {
    const code = match[1].trim();
    if (code.length > 20 && /import |def |class |print\(|#/.test(code)) {
      blocks.push(code);
    }
  }
  return blocks;
}

/**
 * Guess a title from code content (first meaningful comment or first import).
 */
function guessTitleFromCode(code: string, fallback?: string): string {
  const lines = code.split('\n');
  // Look for a comment that looks like a title (not shebang, not too long)
  for (const ln of lines.slice(0, 8)) {
    const trimmed = ln.trim();
    if (trimmed.startsWith('#') && !trimmed.startsWith('#!') && trimmed.length > 3 && trimmed.length < 60) {
      const candidate = trimmed.replace(/^#+\s*/, '').trim();
      if (candidate.length > 3) return candidate;
    }
  }
  // Fall back to first import
  for (const ln of lines) {
    const m = ln.match(/^import (\w+)/);
    if (m) return `${m[1]} Script`;
  }
  return fallback || `Butler Script`;
}

/**
 * Guess pip requirements from code (from comments like "# pip install X" or import statements).
 */
function guessRequirements(code: string): string[] {
  const reqs = new Set<string>();
  // From pip install comments
  const pipMatches = code.matchAll(/pip install ([^\n#]+)/g);
  for (const m of pipMatches) {
    m[1].trim().split(/\s+/).forEach(pkg => {
      if (pkg && !pkg.startsWith('-') && !pkg.startsWith('=')) reqs.add(pkg);
    });
  }
  // From well-known third-party imports
  const thirdParty: Record<string, string> = {
    psutil: 'psutil', requests: 'requests', bs4: 'beautifulsoup4',
    selenium: 'selenium', pyautogui: 'pyautogui', pandas: 'pandas',
    openpyxl: 'openpyxl', PIL: 'pillow', flask: 'flask',
    fastapi: 'fastapi', sqlalchemy: 'sqlalchemy', pymongo: 'pymongo',
    apscheduler: 'apscheduler', watchdog: 'watchdog', schedule: 'schedule',
    pydantic: 'pydantic', httpx: 'httpx', aiohttp: 'aiohttp',
  };
  const importMatches = code.matchAll(/^(?:import|from)\s+(\w+)/gm);
  for (const m of importMatches) {
    const mod = m[1];
    if (thirdParty[mod]) reqs.add(thirdParty[mod]);
  }
  return Array.from(reqs);
}

/**
 * Guess category from code content.
 */
function guessCategory(code: string, tags: string[]): string {
  const text = (code + ' ' + tags.join(' ')).toLowerCase();
  if (/selenium|playwright|browser|chrome|firefox/.test(text)) return 'Web';
  if (/requests|beautifulsoup|scrape|crawl|http/.test(text)) return 'Web';
  if (/pyautogui|win32|keyboard|mouse|click/.test(text)) return 'GUI';
  if (/pandas|csv|excel|openpyxl|dataframe/.test(text)) return 'Data';
  if (/pathlib|shutil|os\.path|folder|rename/.test(text)) return 'Files';
  if (/psutil|cpu|ram|memory|monitor/.test(text)) return 'Monitoring';
  if (/schedule|apscheduler|cron|interval/.test(text)) return 'Scheduling';
  if (/smtp|email|send.*mail/.test(text)) return 'Email';
  if (/socket|network|ping|ip/.test(text)) return 'Network';
  if (/subprocess|winreg|startup|install/.test(text)) return 'System';
  return 'AI Generated';
}

/**
 * Save a Butler-generated script to persistent storage.
 */
export async function saveButlerScript(
  code: string,
  opts?: {
    title?: string;
    description?: string;
    tags?: string[];
    notes?: string;
  }
): Promise<ButlerScript> {
  const requirements = guessRequirements(code);
  const tags = opts?.tags ?? ['ai-generated', 'butler'];
  const category = guessCategory(code, tags);
  const title = opts?.title || guessTitleFromCode(code, 'Butler AI Script');
  const timestamp = new Date().toLocaleString();

  const script: ButlerScript = {
    id: `butler-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    title,
    script: code,
    category,
    description: opts?.description || `Generated by Butler AI on ${timestamp}`,
    tags,
    requirements,
    createdAt: new Date().toISOString(),
    source: 'butler_ai',
    notes: opts?.notes || '',
  };

  const existing = await loadButlerScripts();
  // Deduplicate by trimmed code
  const deduped = existing.filter(s => s.script.trim() !== code.trim());
  const updated = [script, ...deduped];
  await AsyncStorage.setItem(BUTLER_SCRIPTS_KEY, JSON.stringify(updated));
  return script;
}

/**
 * Load all Butler-generated scripts from storage.
 */
export async function loadButlerScripts(): Promise<ButlerScript[]> {
  try {
    const raw = await AsyncStorage.getItem(BUTLER_SCRIPTS_KEY);
    if (!raw) return [];
    return JSON.parse(raw) as ButlerScript[];
  } catch {
    return [];
  }
}

/**
 * Delete a Butler-generated script by ID.
 */
export async function deleteButlerScript(id: string): Promise<void> {
  const existing = await loadButlerScripts();
  const updated = existing.filter(s => s.id !== id);
  await AsyncStorage.setItem(BUTLER_SCRIPTS_KEY, JSON.stringify(updated));
}

/**
 * Update an existing Butler script (title, script content, description).
 */
export async function updateButlerScript(
  id: string,
  changes: Partial<Pick<ButlerScript, 'title' | 'script' | 'description' | 'category' | 'notes'>>
): Promise<void> {
  const existing = await loadButlerScripts();
  const updated  = existing.map(s =>
    s.id === id ? { ...s, ...changes } : s
  );
  await AsyncStorage.setItem(BUTLER_SCRIPTS_KEY, JSON.stringify(updated));
}

/**
 * Clear all Butler-generated scripts.
 */
export async function clearButlerScripts(): Promise<void> {
  await AsyncStorage.removeItem(BUTLER_SCRIPTS_KEY);
}
